-- CreateTable
CREATE TABLE `TAIKHOAN` (
    `maTaiKhoan` INTEGER NOT NULL AUTO_INCREMENT,
    `tenTaiKhoan` VARCHAR(50) NULL,
    `matKhau` VARCHAR(255) NULL,
    `hoVaTen` VARCHAR(100) NULL,
    `ngaySinh` DATE NULL,
    `gioiTinh` VARCHAR(5) NULL,
    `soDienThoai` VARCHAR(10) NULL,
    `email` VARCHAR(100) NULL,
    `diaChi` TEXT NULL,
    `loaiTaiKhoan` VARCHAR(20) NULL,
    `ngayTaoTaiKhoan` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`maTaiKhoan`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NHOM_CO` (
    `maNhomCo` INTEGER NOT NULL AUTO_INCREMENT,
    `tenNhomCo` VARCHAR(100) NULL,
    `moTaNhomCo` TEXT NULL,

    PRIMARY KEY (`maNhomCo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BAITAP_PHUCHOI` (
    `maBaiTap` INTEGER NOT NULL AUTO_INCREMENT,
    `maNhomCo` INTEGER NULL,
    `tenBaiTap` VARCHAR(100) NULL,
    `moTaBaiTap` TEXT NULL,
    `mucDo` VARCHAR(50) NULL,
    `dungCuCanThiet` VARCHAR(50) NULL,
    `videoHuongDan` VARCHAR(255) NULL,

    PRIMARY KEY (`maBaiTap`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BENHNHAN` (
    `maBenhNhan` INTEGER NOT NULL AUTO_INCREMENT,
    `chieuCao` DECIMAL(5, 2) NULL,
    `canNang` DECIMAL(5, 2) NULL,
    `tienSuChanThuong` TEXT NULL,
    `tinhTrangHienTai` TEXT NULL,
    `maTaiKhoan` INTEGER NULL,

    UNIQUE INDEX `BENHNHAN_maTaiKhoan_key`(`maTaiKhoan`),
    PRIMARY KEY (`maBenhNhan`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BACSI` (
    `maBacSi` INTEGER NOT NULL AUTO_INCREMENT,
    `chuyenKhoa` VARCHAR(100) NULL,
    `congTac` VARCHAR(100) NULL,
    `ngayBatDau` DATE NULL,
    `maTaiKhoan` INTEGER NULL,

    UNIQUE INDEX `BACSI_maTaiKhoan_key`(`maTaiKhoan`),
    PRIMARY KEY (`maBacSi`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KYTHUATVIEN` (
    `maKyThuatVien` INTEGER NOT NULL AUTO_INCREMENT,
    `chungChi` TEXT NULL,
    `ngayBatDau` DATE NULL,
    `maTaiKhoan` INTEGER NULL,

    UNIQUE INDEX `KYTHUATVIEN_maTaiKhoan_key`(`maTaiKhoan`),
    PRIMARY KEY (`maKyThuatVien`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOSOSO_BENHAN` (
    `maHoSo` INTEGER NOT NULL AUTO_INCREMENT,
    `maBenhNhan` INTEGER NULL,
    `maBacSi` INTEGER NULL,
    `ngayLapHoSo` DATE NULL,
    `chanDoan` TEXT NULL,
    `trangThaiHienTai` VARCHAR(50) NULL,

    PRIMARY KEY (`maHoSo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THONGBAO_LICHTAP` (
    `maLichTap` INTEGER NOT NULL AUTO_INCREMENT,
    `maHoSo` INTEGER NULL,
    `maTaiKhoan` INTEGER NULL,
    `ngayTap` DATE NULL,
    `gioBatDau` TIME NULL,
    `trangThai` VARCHAR(20) NULL,
    `daDoc` TINYINT NULL DEFAULT 0,
    `phuongThuc` VARCHAR(20) NULL,
    `ghiChu` TEXT NULL,

    PRIMARY KEY (`maLichTap`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHANCONG` (
    `maPhanCong` INTEGER NOT NULL AUTO_INCREMENT,
    `maHoSo` INTEGER NULL,
    `maKyThuatVien` INTEGER NULL,
    `ngayBatDau` DATE NULL,
    `ngayKetThuc` DATE NULL,

    PRIMARY KEY (`maPhanCong`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MUCTIEU_DIEUTRI` (
    `maMucTieu` INTEGER NOT NULL AUTO_INCREMENT,
    `maHoSo` INTEGER NULL,
    `noiDung` TEXT NULL,
    `trangThai` VARCHAR(20) NULL,
    `mucDoUuTien` VARCHAR(20) NULL,
    `ngayDatMucTieu` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`maMucTieu`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOTRINH_DIEUTRI` (
    `maLoTrinh` INTEGER NOT NULL AUTO_INCREMENT,
    `maMucTieu` INTEGER NULL,
    `maKyThuatVien` INTEGER NULL,
    `tenLoTrinh` VARCHAR(100) NULL,
    `thoiGianBatDau` DATE NULL,
    `thoiGianKetThuc` DATE NULL,
    `ghiChu` TEXT NULL,

    PRIMARY KEY (`maLoTrinh`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KEHOACH_DIEUTRI` (
    `maKeHoach` INTEGER NOT NULL AUTO_INCREMENT,
    `maLoTrinh` INTEGER NULL,
    `tenKeHoach` VARCHAR(100) NULL,
    `moTa` TEXT NULL,
    `thoiGianBatDau` DATE NULL,
    `thoiGianKetThuc` DATE NULL,

    PRIMARY KEY (`maKeHoach`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHITIET_KEHOACH` (
    `maChiTiet` INTEGER NOT NULL AUTO_INCREMENT,
    `maKeHoach` INTEGER NULL,
    `maBaiTap` INTEGER NULL,
    `sets` INTEGER NULL,
    `reps` INTEGER NULL,
    `cuongDo` VARCHAR(20) NULL,
    `ghiChu` TEXT NULL,

    PRIMARY KEY (`maChiTiet`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BAOCAO_LUYENTAP` (
    `maBaoCao` INTEGER NOT NULL AUTO_INCREMENT,
    `maKeHoach` INTEGER NULL,
    `ngayLuyenTap` DATE NULL,
    `thoiLuong` INTEGER NULL,
    `mucDoDau` INTEGER NULL,
    `danhGiaSoBo` TEXT NULL,

    PRIMARY KEY (`maBaoCao`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DANHGIA_TIENTRIEN` (
    `maDanhGia` INTEGER NOT NULL AUTO_INCREMENT,
    `maHoSo` INTEGER NULL,
    `ngayDanhGia` DATE NULL,
    `chiTiet` TEXT NULL,
    `thangDiem` DECIMAL(4, 2) NULL,
    `daDoc` BOOLEAN NOT NULL DEFAULT false,
    `loaiDanhGia` VARCHAR(191) NOT NULL DEFAULT 'BAC_SI',
    `ketQua` BOOLEAN NULL,
    `maKyThuatVien` INTEGER NULL,

    PRIMARY KEY (`maDanhGia`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CAMNANG_THUOC` (
    `maThuoc` INTEGER NOT NULL AUTO_INCREMENT,
    `tenThuoc` VARCHAR(100) NULL,
    `congDung` TEXT NULL,

    PRIMARY KEY (`maThuoc`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CAMNANG_THUCPHAM` (
    `maThucPham` INTEGER NOT NULL AUTO_INCREMENT,
    `tenThucPham` VARCHAR(100) NULL,
    `chiTiet` TEXT NULL,

    PRIMARY KEY (`maThucPham`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHITIET_SUDUNG` (
    `maSuDung` INTEGER NOT NULL AUTO_INCREMENT,
    `maHoSo` INTEGER NULL,
    `loai` VARCHAR(20) NULL,
    `maThuoc` INTEGER NULL,
    `maThucPham` INTEGER NULL,
    `lieuLuong` TEXT NULL,
    `huongDanSuDung` TEXT NULL,

    PRIMARY KEY (`maSuDung`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BAITAP_PHUCHOI` ADD CONSTRAINT `BAITAP_PHUCHOI_maNhomCo_fkey` FOREIGN KEY (`maNhomCo`) REFERENCES `NHOM_CO`(`maNhomCo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BENHNHAN` ADD CONSTRAINT `BENHNHAN_maTaiKhoan_fkey` FOREIGN KEY (`maTaiKhoan`) REFERENCES `TAIKHOAN`(`maTaiKhoan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BACSI` ADD CONSTRAINT `BACSI_maTaiKhoan_fkey` FOREIGN KEY (`maTaiKhoan`) REFERENCES `TAIKHOAN`(`maTaiKhoan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KYTHUATVIEN` ADD CONSTRAINT `KYTHUATVIEN_maTaiKhoan_fkey` FOREIGN KEY (`maTaiKhoan`) REFERENCES `TAIKHOAN`(`maTaiKhoan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOSOSO_BENHAN` ADD CONSTRAINT `HOSOSO_BENHAN_maBenhNhan_fkey` FOREIGN KEY (`maBenhNhan`) REFERENCES `BENHNHAN`(`maBenhNhan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOSOSO_BENHAN` ADD CONSTRAINT `HOSOSO_BENHAN_maBacSi_fkey` FOREIGN KEY (`maBacSi`) REFERENCES `BACSI`(`maBacSi`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THONGBAO_LICHTAP` ADD CONSTRAINT `THONGBAO_LICHTAP_maHoSo_fkey` FOREIGN KEY (`maHoSo`) REFERENCES `HOSOSO_BENHAN`(`maHoSo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THONGBAO_LICHTAP` ADD CONSTRAINT `THONGBAO_LICHTAP_maTaiKhoan_fkey` FOREIGN KEY (`maTaiKhoan`) REFERENCES `TAIKHOAN`(`maTaiKhoan`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHANCONG` ADD CONSTRAINT `PHANCONG_maHoSo_fkey` FOREIGN KEY (`maHoSo`) REFERENCES `HOSOSO_BENHAN`(`maHoSo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHANCONG` ADD CONSTRAINT `PHANCONG_maKyThuatVien_fkey` FOREIGN KEY (`maKyThuatVien`) REFERENCES `KYTHUATVIEN`(`maKyThuatVien`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MUCTIEU_DIEUTRI` ADD CONSTRAINT `MUCTIEU_DIEUTRI_maHoSo_fkey` FOREIGN KEY (`maHoSo`) REFERENCES `HOSOSO_BENHAN`(`maHoSo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LOTRINH_DIEUTRI` ADD CONSTRAINT `LOTRINH_DIEUTRI_maMucTieu_fkey` FOREIGN KEY (`maMucTieu`) REFERENCES `MUCTIEU_DIEUTRI`(`maMucTieu`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LOTRINH_DIEUTRI` ADD CONSTRAINT `LOTRINH_DIEUTRI_maKyThuatVien_fkey` FOREIGN KEY (`maKyThuatVien`) REFERENCES `KYTHUATVIEN`(`maKyThuatVien`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KEHOACH_DIEUTRI` ADD CONSTRAINT `KEHOACH_DIEUTRI_maLoTrinh_fkey` FOREIGN KEY (`maLoTrinh`) REFERENCES `LOTRINH_DIEUTRI`(`maLoTrinh`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIET_KEHOACH` ADD CONSTRAINT `CHITIET_KEHOACH_maKeHoach_fkey` FOREIGN KEY (`maKeHoach`) REFERENCES `KEHOACH_DIEUTRI`(`maKeHoach`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIET_KEHOACH` ADD CONSTRAINT `CHITIET_KEHOACH_maBaiTap_fkey` FOREIGN KEY (`maBaiTap`) REFERENCES `BAITAP_PHUCHOI`(`maBaiTap`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BAOCAO_LUYENTAP` ADD CONSTRAINT `BAOCAO_LUYENTAP_maKeHoach_fkey` FOREIGN KEY (`maKeHoach`) REFERENCES `KEHOACH_DIEUTRI`(`maKeHoach`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANHGIA_TIENTRIEN` ADD CONSTRAINT `DANHGIA_TIENTRIEN_maKyThuatVien_fkey` FOREIGN KEY (`maKyThuatVien`) REFERENCES `KYTHUATVIEN`(`maKyThuatVien`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANHGIA_TIENTRIEN` ADD CONSTRAINT `DANHGIA_TIENTRIEN_maHoSo_fkey` FOREIGN KEY (`maHoSo`) REFERENCES `HOSOSO_BENHAN`(`maHoSo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIET_SUDUNG` ADD CONSTRAINT `CHITIET_SUDUNG_maHoSo_fkey` FOREIGN KEY (`maHoSo`) REFERENCES `HOSOSO_BENHAN`(`maHoSo`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIET_SUDUNG` ADD CONSTRAINT `CHITIET_SUDUNG_maThuoc_fkey` FOREIGN KEY (`maThuoc`) REFERENCES `CAMNANG_THUOC`(`maThuoc`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHITIET_SUDUNG` ADD CONSTRAINT `CHITIET_SUDUNG_maThucPham_fkey` FOREIGN KEY (`maThucPham`) REFERENCES `CAMNANG_THUCPHAM`(`maThucPham`) ON DELETE SET NULL ON UPDATE CASCADE;
